alias gits='git status'
alias gitall='git add -A'
alias gitcm='git commit -m'
alias gitchk='git checkout'

alias :q='echo idiot'
alias :q!='echo idiot'
alias :wq='echo idiot'

alias rg='ranger'

alias tbl='toolbox list'
alias tbs='toolbox start'
alias tbst='podman stop'
alias tbe='toolbox enter'
alias tbr='toolbox run -c'

alias pm='podman'

alias vimbg='vim -p mountainblade.c entities.h entities.c logic.h logic.c actions.h actions.c display.h display.c gtime.h gtime.c'
