alias gits='git status'
alias gitall='git add -A'
alias gitcm='git commit -m'
alias gitchk='git checkout'

alias :q='echo idiot'
alias :q!='echo idiot'
alias :wq='echo idiot'

alias rg='ranger'

alias tbl='toolbox list'
alias tbs='toolbox start'
alias tbst='podman stop'
alias tbe='toolbox enter'
alias tbr='toolbox run -c'

alias pm='podman'

alias cdr='cd $HOME/repos'

docmd () {
	pandoc -f docx -t markdown "$1" -o "$1".md
}
mddoc () {
	pandoc -f markdown -t docx "$1" -o "$1".docx
}

